version: '3.8'

services:
  submission-service:
    build: ./backend/submission-service
    ports:
      - "3002:3002"
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=ndiaye
      - MYSQL_PASSWORD=ndiaye111
      - MYSQL_DATABASE=plateforme_evaluation_db
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ndiaye111
      MYSQL_DATABASE: plateforme_evaluation_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: